const API='https://treasure-tempest-online.treasure-tempest-online.workers.dev';
const $=s=>document.querySelector(s),app=$('#app'),connection=$('#connection');
let credential=localStorage.getItem('tt-online-credential')||'',account=null,catalog=[],socket=null,room=null,roomId='',timer=null,lobbyDraft=null;
let activeProfile=null,profileReturn='home',leaderboardReturn='home';
const requestedView=new URLSearchParams(location.search).get('view');
const embedded=self!==top||new URLSearchParams(location.search).get('embedded')==='1',intent=new URLSearchParams(location.search).get('intent');
let lobbyMusic=null;
const AVATARS=['Pirate',...Array.from({length:9},(_,i)=>`Pirate ${i+2}`)];
const deviceId=localStorage.getItem('tt-device-id')||crypto.randomUUID();localStorage.setItem('tt-device-id',deviceId);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function prepareLobbyMusic(){
 if(embedded)return;
 try{const playlist=await fetch('assets/audio/playlist.json',{cache:'no-cache'}).then(r=>r.json()),selected=localStorage.getItem('tt-song')||playlist.default,track=playlist.tracks.find(t=>t.id===selected)||playlist.tracks.find(t=>t.id===playlist.default)||playlist.tracks[0];if(!track)return;lobbyMusic=new Audio(track.src);lobbyMusic.loop=true;lobbyMusic.preload='auto';lobbyMusic.volume=Math.max(0,Math.min(1,Number(localStorage.getItem('tt-music-volume')??.25)));const saved=JSON.parse(sessionStorage.getItem('tt-music-continuity')||'null');if(saved?.id===track.id){const resume=Math.max(0,Number(saved.time)||0)+(Date.now()-(Number(saved.at)||Date.now()))/1000;lobbyMusic.addEventListener('loadedmetadata',()=>{lobbyMusic.currentTime=lobbyMusic.duration?resume%lobbyMusic.duration:resume},{once:true})}lobbyMusic.play().catch(()=>{})}catch{}
}
function saveLobbyMusic(){if(lobbyMusic)sessionStorage.setItem('tt-music-continuity',JSON.stringify({id:localStorage.getItem('tt-song'),time:lobbyMusic.currentTime,at:Date.now()}))}
addEventListener('pagehide',saveLobbyMusic);setInterval(saveLobbyMusic,1000);
function unlockLobbyMusic(){if(lobbyMusic?.paused&&lobbyMusic.volume>0)lobbyMusic.play().catch(()=>{})}
document.addEventListener('pointerdown',unlockLobbyMusic,{passive:true});
document.addEventListener('keydown',unlockLobbyMusic);
function toast(text){const e=$('#toast');e.textContent=text;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2800)}
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(credential)headers.Authorization=`Bearer ${credential}`;const safeRead=!options.method||options.method==='GET';let lastError;for(let attempt=0;attempt<(safeRead?6:1);attempt++){try{const r=await fetch(API+path,{...options,headers}),data=await r.json().catch(()=>({error:'The online harbor did not answer.'}));if(r.ok)return data;const e=new Error(data.error||'Request failed.');e.status=r.status;if(!safeRead||r.status<500)throw e;lastError=e}catch(error){lastError=error;if(!safeRead||error.status&&error.status<500)throw error}if(attempt<5)await new Promise(resolve=>setTimeout(resolve,180*(attempt+1)))}const e=new Error('The online harbor could not be reached. Your captain is still saved on this device.');e.status=lastError?.status||0;throw e}
function image(power){if(power==='Pirate')return'assets/pirate-profile-default.png';const match=/^Pirate (\d+)$/.exec(power);if(match)return`assets/profile-pirates/pirate-${String(match[1]).padStart(2,'0')}.png`;return`assets/powers-expansion/${power.toLowerCase().replaceAll(' ','_')}.webp`}
async function boot(){prepareLobbyMusic();catalog=(await fetch('catalog.json').then(r=>r.json())).powers;if(credential){try{account=await api('/api/account/me')}catch(err){if(err.status===400){credential='';localStorage.removeItem('tt-online-credential')}else throw err}}const requested=new URLSearchParams(location.search).get('room');if(account&&requested){roomId=requested.toUpperCase();connectRoom()}else if(account&&requestedView==='leaderboard')leaderboard('exit');else if(account&&requestedView==='profile')captainProfile(account,'exit');else account?home():signIn()}
function signIn(){app.innerHTML=`<section class="panel hero"><img class="avatar profile-circle" src="${image('Pirate')}" alt="Pirate profile icon"><div class="muted">ONE CAPTAIN PER DEVICE</div><h1>CREATE YOUR CAPTAIN</h1><p>Choose a unique captain name. No email or password is required.</p><div class="stack"><input id="username" maxlength="20" placeholder="Captain name"><button class="primary" data-act="create-account">Create captain</button><button data-act="show-recover">Recover an existing captain</button><button data-act="exit-online">Return home</button></div></section>`}
function recoveryForm(){app.innerHTML=`<section class="panel hero"><h1>Recover captain</h1><div class="stack"><input id="username" maxlength="20" placeholder="Captain name"><input id="recovery" placeholder="XXXX-XXXX-XXXX-XXXX"><button class="primary" data-act="recover">Recover on this device</button><button data-act="signin">Back</button></div></section>`}
function saveAuth(data){credential=data.credential;account=data.account;localStorage.setItem('tt-online-credential',credential);if(embedded&&intent==='local'){parent.postMessage({type:'tt-account-ready',intent:'local'},location.origin);return}requestedView==='leaderboard'?leaderboard('exit'):requestedView==='profile'?captainProfile(account,'exit'):home()}
async function home(){app.innerHTML=`<section class="harbor-hub"><div class="harbor-heading"><span class="muted">THE ONLINE HARBOR</span><h1>Choose your voyage.</h1><p>Create a fresh room for your crew, or enter a six-character room code to join friends already waiting at the docks.</p></div><div class="harbor-actions"><article class="voyage-option create-voyage"><div class="voyage-icon">⚓</div><span class="muted">CAPTAIN A NEW CREW</span><h2>Create a room</h2><p>You become host and choose the voyage size, turn length, and bot behavior.</p><button class="primary" data-act="create-room">Open a new room</button></article><article class="voyage-option join-voyage"><div class="voyage-icon">✦</div><span class="muted">JOIN YOUR FLEET</span><h2>Enter a room code</h2><p>Ask the host for the six-character code shown in their harbor.</p><div class="join-code"><input id="room-code" maxlength="6" autocomplete="off" placeholder="ROOM CODE" aria-label="Room code"><button data-act="join-room">Join voyage</button></div></article></div><div class="harbor-note">Online rooms begin with at least two real captains on separate devices. Empty seats are filled by bots when the host starts the voyage.</div></section>`}
function backButton(destination){return `<button data-act="${destination==='exit'?'exit-online':destination==='leaderboard'?'back-leaderboard':'home'}">Back</button>`}
async function leaderboard(returnTo='home'){leaderboardReturn=returnTo;const board=await api('/api/leaderboard').catch(()=>({scores:[]}));app.innerHTML=`<section class="panel stack"><div class="row between"><h1>Leaderboard</h1>${backButton(returnTo)}</div><table class="leaderboard"><thead><tr><th>#</th><th>Captain</th><th>Power</th><th>Gold</th></tr></thead><tbody>${board.scores.map((s,i)=>`<tr><td>${i+1}</td><td><button class="captain-link" data-profile-id="${esc(s.account_id)}">${esc(s.username)}</button></td><td>${esc(s.power)}</td><td>${Number(s.score).toLocaleString()}</td></tr>`).join('')||'<tr><td colspan="4">No qualifying voyages yet.</td></tr>'}</tbody></table></section>`}
function captainProfile(profile,returnTo='home'){activeProfile=profile;profileReturn=returnTo;const mine=profile.id===account.id;app.innerHTML=`<section class="panel stack captain-profile"><div class="row between"><div class="profile-identity"><button class="avatar-button" ${mine?'data-act="avatars"':''} aria-label="${mine?'Choose profile picture':'Captain portrait'}"><img class="avatar profile-circle" src="${image(profile.avatarPower)}"></button><div><span class="muted">CAPTAIN PROFILE</span><h1>${esc(profile.username)}</h1></div></div>${backButton(returnTo)}</div><div class="cards"><button class="card stat-card" data-profile-view="wins"><strong>${profile.totalWins}</strong><div class="muted">Total wins</div></button><button class="card stat-card" data-profile-view="scores"><strong>${Number(profile.highScore).toLocaleString()}</strong><div class="muted">Highest gold</div></button><button class="card stat-card" data-profile-view="badges"><strong>${profile.achievements.length}</strong><div class="muted">Badges earned</div></button></div>${mine?'<div class="row"><button data-act="settings">Player settings</button></div>':''}</section>`}
async function loadCaptainProfile(id){captainProfile(id===account.id?account:await api(`/api/profile/${encodeURIComponent(id)}`),'leaderboard')}
function profileWins(){app.innerHTML=`<section class="panel stack"><div class="row between"><h1>${esc(activeProfile.username)} · Wins by power</h1><button data-act="back-profile">Back</button></div><div class="cards">${catalog.map(p=>`<div class="card stat-line"><span>${esc(p.name)}</span><strong>${activeProfile.powerWins.find(x=>x.power===p.name)?.wins||0}</strong></div>`).join('')}</div></section>`}
function profileScores(){app.innerHTML=`<section class="panel stack"><div class="row between"><h1>${esc(activeProfile.username)} · Highest gold by power</h1><button data-act="back-profile">Back</button></div><div class="cards">${catalog.map(p=>`<div class="card stat-line"><span>${esc(p.name)}</span><strong>${Number(activeProfile.powerHighScores?.find(x=>x.power===p.name)?.high_score||0).toLocaleString()}</strong></div>`).join('')}</div></section>`}
async function profileBadges(){const data=await api('/api/achievements'),won=new Set(activeProfile.achievements.map(x=>x.achievement_id));app.innerHTML=`<section class="panel stack"><div class="row between"><h1>${esc(activeProfile.username)} · Achievements</h1><button data-act="back-profile">Back</button></div><div class="badge-grid">${data.achievements.map((a,i)=>`<article class="achievement ${won.has(a.id)?'earned':'locked'}"><span class="badge">${won.has(a.id)?['⚓','★','♛','✦'][i%4]:'?'}</span><div><strong>${esc(a.name)}</strong><p>${esc(a.description)}</p></div></article>`).join('')}</div></section>`}
function winsBreakdown(){app.innerHTML=`<section class="panel stack"><div class="row between"><h1>Wins by power</h1><button data-act="home">Back</button></div><div class="cards">${catalog.map(p=>`<div class="card stat-line"><span>${esc(p.name)}</span><strong>${account.powerWins.find(x=>x.power===p.name)?.wins||0}</strong></div>`).join('')}</div></section>`}
function highscoresBreakdown(){app.innerHTML=`<section class="panel stack"><div class="row between"><h1>Highest gold by power</h1><button data-act="home">Back</button></div><div class="cards">${catalog.map(p=>`<div class="card stat-line"><span>${esc(p.name)}</span><strong>${account.powerHighScores?.find(x=>x.power===p.name)?.high_score||0}</strong></div>`).join('')}</div></section>`}
async function achievements(){const data=await api('/api/achievements');const won=new Set(account.achievements.map(x=>x.achievement_id));app.innerHTML=`<section class="panel stack"><div class="row between"><h1>Achievements</h1><button data-act="home">Back</button></div><div class="badge-grid">${data.achievements.map((a,i)=>`<article class="achievement ${won.has(a.id)?'earned':'locked'}"><span class="badge">${won.has(a.id)?['⚓','★','♛','✦'][i%4]:'?'}</span><div><strong>${esc(a.name)}</strong><p>${esc(a.description)}</p></div></article>`).join('')}</div></section>`}
function avatars(){app.innerHTML=`<section class="panel stack"><div class="row between"><h1>Choose your pirate</h1><button data-act="home">Back</button></div><div class="portrait-picker">${AVATARS.map((name,i)=>`<button class="portrait-choice ${account.avatarPower===name?'selected':''}" data-avatar="${esc(name)}" aria-label="Pirate ${i+1}"><img src="${image(name)}" alt="Pirate ${i+1}"><span>Pirate ${i+1}</span></button>`).join('')}</div></section>`}
function settings(){app.innerHTML=`<section class="panel stack"><div class="row between"><h1>Player settings</h1><button data-act="home">Back</button></div><h2>Account recovery</h2><p class="muted">Generate a private recovery code when you are ready to protect this captain. Creating a new code replaces any older one.</p><button data-act="recovery-code">Show a new recovery code</button><div id="recovery-result"></div><div class="notice">Logging out removes this captain from this device. Generate and save a recovery code first if you want to return later.</div><button class="danger" data-act="logout">Log out</button></section>`}
async function createRoom(){const d=await api('/api/rooms/create',{method:'POST',body:JSON.stringify({deviceId})});roomId=d.roomId;connectRoom()}
function joinRoom(){roomId=$('#room-code').value.trim().toUpperCase();if(roomId.length!==6)return toast('Enter the six-character room code.');connectRoom()}
function connectRoom(){localStorage.setItem('tt-online-room',roomId);if(socket)socket.close();const url=`${API.replace('https','wss')}/api/rooms/${roomId}/ws?deviceId=${encodeURIComponent(deviceId)}`;socket=new WebSocket(url,`tt-auth.${credential}`);connection.textContent='Connecting…';socket.onopen=()=>{connection.textContent='Connected';connection.className='pill live'};socket.onclose=()=>{connection.textContent='Reconnecting…';connection.className='pill bad';setTimeout(()=>roomId&&connectRoom(),1800)};socket.onerror=()=>toast('Could not reach that room.');socket.onmessage=e=>{const msg=JSON.parse(e.data);if(msg.type==='error')toast(msg.message);if(msg.type==='state'){room=msg.state;renderRoom()}}}
const send=data=>socket?.readyState===1&&socket.send(JSON.stringify(data));
document.addEventListener('pointerdown',e=>{if(e.target.closest('[data-act="leave-room"]'))send({type:'leave'})},{capture:true});
function renderRoom(){clearInterval(timer);if(room.phase==='lobby')renderLobby();else if(room.phase==='choosing')renderPowerChoice();else{localStorage.setItem('tt-online-room',roomId);location.href=`index.html?online=${encodeURIComponent(roomId)}${embedded?'&embedded=1':''}`}}
function renderLobby(){const host=room.hostId===account.id;if(host&&!lobbyDraft)lobbyDraft={totalPlayers:Math.max(room.totalPlayers,room.members.length),timeFormat:room.timeFormat||'long',botActions:room.botActions||'fast'};if(host&&lobbyDraft.totalPlayers<room.members.length)lobbyDraft.totalPlayers=room.members.length;const s=host?lobbyDraft:room,reason=room.members.length<2?'At least two real players on separate devices must join.':'';app.innerHTML=`<section class="grid"><div class="panel stack"><div class="row between"><div><div class="muted">ROOM CODE</div><div class="room-code">${roomId}</div></div><button data-act="leave-room">Leave</button></div>${host?`<div class="row"><label>Total players<select id="total">${[3,4,5,6,7,8].filter(n=>n>=room.members.length).map(n=>`<option ${n===s.totalPlayers?'selected':''}>${n}</option>`)}</select></label><label>Turn time<select id="time-format">${[['short','Short · 10 sec'],['medium','Medium · 30 sec'],['long','Long · 1 min']].map(([v,l])=>`<option value="${v}" ${v===s.timeFormat?'selected':''}>${l}</option>`)}</select></label><label>Bot actions<select id="bot-actions">${[['fast','Fast · draw at 5 sec'],['slow','Slow · draw at 10 sec'],['controlled','Controlled by host']].map(([v,l])=>`<option value="${v}" ${v===s.botActions?'selected':''}>${l}</option>`)}</select></label><button data-act="configure">Update room</button></div>`:`<p class="muted">${room.totalPlayers} total captains · missing seats become bots · ${esc((room.timeFormat||'long').toUpperCase())} turns · ${esc((room.botActions||'fast').toUpperCase())} bots.</p>`}<div><h2>Crew</h2>${room.members.map(m=>`<div class="member"><div><strong>${esc(m.username)}</strong> ${m.accountId===room.hostId?'⚓':''}<br><small>${m.connected?'Connected':'Disconnected'}</small></div>${host&&m.accountId!==account.id?`<div><button data-member="${m.accountId}" data-act="${m.muted?'unmute':'mute'}">${m.muted?'Unmute':'Mute'}</button> <button data-member="${m.accountId}" data-act="kick">Kick</button> <button class="danger" data-member="${m.accountId}" data-act="ban">Ban</button></div>`:''}</div>`).join('')}</div>${host?`<div class="notice">${esc(reason||`${room.totalPlayers-room.members.length} bot${room.totalPlayers-room.members.length===1?'':'s'} will fill the remaining seats. Power choices begin after Start Voyage.`)}</div><button class="primary" data-act="start-online" ${reason?'disabled':''}>Start voyage</button>`:'<p>Waiting for the host to start the voyage…</p>'}</div>${chatPanel()}</section>`}
function renderPowerChoice(){const me=room.members.find(m=>m.accountId===account.id),offers=me?.offers||[];app.innerHTML=`<div class="power-lock"><section class="power-lock-card"><span class="muted">PRIVATE CAPTAIN CHOICE</span><h1>Choose your power</h1><div id="power-clock" class="room-code"></div><p>Only you can see these two choices. One is chosen randomly when time runs out.</p><div class="cards power-offers">${offers.map(name=>{const p=catalog.find(x=>x.name===name);return `<button class="power ${me.power===name?'selected':''}" data-power="${esc(name)}" ${me.power?'disabled':''}><img src="${image(name)}"><h2>${esc(name)}</h2><p>${esc(p?.description||'')}</p></button>`}).join('')}</div>${me?.power?'<div class="notice">Power locked in. Waiting for the other captains…</div>':''}</section></div>`;const tick=()=>{const e=$('#power-clock');if(e)e.textContent=Math.ceil(Math.max(0,(room.powerDeadline-Date.now())/1000))+'s'};tick();timer=setInterval(tick,250)}
function chatPanel(){return `<aside class="panel stack"><h2>Room chat</h2><div class="chat" id="chat">${room.chat.map(m=>`<p><strong>${esc(m.username)}</strong> ${esc(m.text)}</p>`).join('')}</div><div class="row"><input id="chat-input" maxlength="240" placeholder="Message the fleet"><button data-act="chat">Send</button></div></aside>`}
function renderGame(){const s=room.snapshot,g=s?.game,req=s?.request;if(!g)return;const deadline=room.turnDeadline||0;app.innerHTML=`<section class="grid"><div class="panel stack"><div class="row between"><div><span class="muted">ROUND ${g.round}/${g.maxRounds}</span><h1>${g.safe?'Calm waters':'The storm'}</h1></div><div><div class="muted">Shared pot</div><div class="room-code">${Math.round(g.pot)} gold</div></div></div><div class="players">${g.players.map((p,i)=>`<div class="player ${i===g.current?'current':''}"><strong>${esc(p.name)}</strong><div>${esc(p.power)}</div><div class="numbers"><span>⛵ ${p.ships}</span><span>◈ ${Math.round(p.gold)}</span></div><small>${esc(p.status)}</small></div>`).join('')}</div>${g.last?`<div class="card"><span class="muted">Last card</span><h2>${esc(g.last.name||g.last.kind||g.last)}</h2></div>`:''}<div class="prompt"><div id="timer" class="timer"></div><h2>${esc(req?.title||'Voyage complete')}</h2><p class="detail">${esc(req?.detail||'Final fortunes have been counted.')}</p><div class="row" style="justify-content:center">${(req?.options||[]).map(o=>`<button class="${o.value==='stay'?'primary':''}" data-answer="${esc(o.value)}">${esc(o.label)}</button>`).join('')}</div></div></div>${chatPanel()}</section>`;const tick=()=>{const e=$('#timer');if(!e)return;const left=Math.max(0,deadline-Date.now());e.textContent=req?.kind==='turn'?`${(left/1000).toFixed(1)}s`:'';document.querySelectorAll('[data-answer="stay"]').forEach(b=>b.disabled=Date.now()<(room.drawAllowedAt||0))};tick();timer=setInterval(tick,100)}
document.addEventListener('change',e=>{if(!lobbyDraft)return;const ids={total:'totalPlayers','time-format':'timeFormat','bot-actions':'botActions'},key=ids[e.target.id];if(key)lobbyDraft[key]=key==='totalPlayers'?+e.target.value:e.target.value});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{const a=b.dataset.act;if(a==='create-account'){const d=await api('/api/account/create',{method:'POST',body:JSON.stringify({username:$('#username').value})});saveAuth(d)}if(a==='show-recover')recoveryForm();if(a==='recover'){const d=await api('/api/account/recover',{method:'POST',body:JSON.stringify({username:$('#username').value,recoveryCode:$('#recovery').value})});saveAuth(d)}if(a==='signin')signIn();if(a==='home')home();if(a==='wins-breakdown')winsBreakdown();if(a==='highscores-breakdown')highscoresBreakdown();if(a==='achievements')achievements();if(a==='avatars')avatars();if(a==='settings')settings();if(a==='recovery-code'){const d=await api('/api/account/recovery',{method:'POST'});$('#recovery-result').innerHTML=`<div class="recovery">${esc(d.recoveryCode)}</div><p class="muted">Keep this private. It is now the only recovery code for this captain.</p>`}if(a==='logout'){if(!confirm(`Log out ${account.username} on this device? Save a recovery code first if you want to return later.`))return;credential='';account=null;roomId='';socket?.close();socket=null;localStorage.removeItem('tt-online-credential');localStorage.removeItem('tt-online-room');signIn()}if(a==='create-room')await createRoom();if(a==='join-room')joinRoom();if(a==='leave-room'){localStorage.removeItem('tt-online-room');roomId='';socket?.close();socket=null;lobbyDraft=null;home()}if(a==='configure')send({type:'configure',...lobbyDraft});if(a==='deal')send({type:'offerPowers'});if(a==='start-online'){send({type:'configure',...lobbyDraft});send({type:'start'})}if(a==='chat'){const input=$('#chat-input');if(input.value.trim())send({type:'chat',message:input.value});input.value=''}if(['kick','ban','mute','unmute'].includes(a))send({type:a,accountId:b.dataset.member});if(b.dataset.power)send({type:'choosePower',power:b.dataset.power});if(b.dataset.avatar){const d=await api('/api/account/avatar',{method:'POST',body:JSON.stringify({avatarPower:b.dataset.avatar})});account=d.account;avatars()}}catch(err){toast(err.message)}});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.id==='chat-input')document.querySelector('[data-act="chat"]')?.click()});
document.addEventListener('click',async e=>{const button=e.target.closest('button');if(!button)return;try{if(button.dataset.act==='profile')captainProfile(account,'home');if(button.dataset.act==='back-profile')captainProfile(activeProfile,profileReturn);if(button.dataset.act==='back-leaderboard')leaderboard(leaderboardReturn);if(button.dataset.profileId)await loadCaptainProfile(button.dataset.profileId);if(button.dataset.profileView==='wins')profileWins();if(button.dataset.profileView==='scores')profileScores();if(button.dataset.profileView==='badges')await profileBadges()}catch(err){toast(err.message)}});
document.addEventListener('click',e=>{const action=e.target.closest('button')?.dataset.act;if(action==='leaderboard')leaderboard();if(action==='retry-online')location.reload();if(action==='exit-online'){if(embedded)parent.postMessage({type:'tt-close-online'},location.origin);else location.href='index.html'}if(action==='offline-fallback'){if(embedded)parent.postMessage({type:'tt-offline-fallback'},location.origin);else location.href='index.html'}});
const renderLobbyWithCurrentTiming=renderLobby;renderLobby=()=>{renderLobbyWithCurrentTiming();const select=$('#bot-actions');if(select){select.querySelector('[value="fast"]').textContent='Fast · draw at 3 sec';select.querySelector('[value="slow"]').textContent='Slow · draw at 8 sec'}};
const renderOnlineHome=home;home=async()=>{await renderOnlineHome();[...app.querySelectorAll('a[href="index.html"]')].find(link=>link.textContent.trim()==='Offline game')?.remove()};
boot().catch(err=>{app.innerHTML=`<section class="panel hero"><h1>Online harbor unavailable</h1><p class="error">${esc(err.message)}</p><button class="primary" data-act="offline-fallback">Continue with offline play</button><button data-act="retry-online">Try again</button></section>`});
