const API='https://treasure-tempest-online.treasure-tempest-online.workers.dev';
const $=s=>document.querySelector(s),app=$('#app'),connection=$('#connection');
let credential=localStorage.getItem('tt-online-credential')||'',account=null,catalog=[],socket=null,room=null,roomId='',timer=null,lobbyDraft=null;
const requestedView=new URLSearchParams(location.search).get('view');
let lobbyMusic=null;
const deviceId=localStorage.getItem('tt-device-id')||crypto.randomUUID();localStorage.setItem('tt-device-id',deviceId);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function prepareLobbyMusic(){
 try{const playlist=await fetch('assets/audio/playlist.json',{cache:'no-cache'}).then(r=>r.json()),selected=localStorage.getItem('tt-song')||playlist.default,track=playlist.tracks.find(t=>t.id===selected)||playlist.tracks.find(t=>t.id===playlist.default)||playlist.tracks[0];if(!track)return;lobbyMusic=new Audio(track.src);lobbyMusic.loop=true;lobbyMusic.preload='auto';lobbyMusic.volume=Math.max(0,Math.min(1,Number(localStorage.getItem('tt-music-volume')??.25)));lobbyMusic.play().catch(()=>{})}catch{}
}
function unlockLobbyMusic(){if(lobbyMusic?.paused&&lobbyMusic.volume>0)lobbyMusic.play().catch(()=>{})}
document.addEventListener('pointerdown',unlockLobbyMusic,{passive:true});
document.addEventListener('keydown',unlockLobbyMusic);
function toast(text){const e=$('#toast');e.textContent=text;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2800)}
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(credential)headers.Authorization=`Bearer ${credential}`;const r=await fetch(API+path,{...options,headers});const data=await r.json().catch(()=>({error:'The online harbor did not answer.'}));if(!r.ok)throw new Error(data.error||'Request failed.');return data}
function image(power){return power==='Pirate'?'assets/pirate-profile-default.png':`assets/powers-expansion/${power.toLowerCase().replaceAll(' ','_')}.webp`}
async function boot(){prepareLobbyMusic();catalog=(await fetch('catalog.json').then(r=>r.json())).powers;if(credential){try{account=await api('/api/account/me')}catch{credential='';localStorage.removeItem('tt-online-credential')}}const requested=new URLSearchParams(location.search).get('room');if(account&&requested){roomId=requested.toUpperCase();connectRoom()}else if(account&&requestedView==='profile')profile();else account?home():signIn()}
function signIn(){app.innerHTML=`<section class="panel hero"><img class="avatar profile-circle" src="${image('Pirate')}" alt="Pirate profile icon"><div class="muted">ONE CAPTAIN PER DEVICE</div><h1>ONLINE VOYAGES</h1><p>Choose a unique captain name. No email or password is required.</p><div class="stack"><input id="username" maxlength="20" placeholder="Captain name"><button class="primary" data-act="create-account">Create captain</button><button data-act="show-recover">Recover an existing captain</button><a href="index.html" class="muted">Return to offline play</a></div></section>`}
function recoveryForm(){app.innerHTML=`<section class="panel hero"><h1>Recover captain</h1><div class="stack"><input id="username" maxlength="20" placeholder="Captain name"><input id="recovery" placeholder="XXXX-XXXX-XXXX-XXXX"><button class="primary" data-act="recover">Recover on this device</button><button data-act="signin">Back</button></div></section>`}
function saveAuth(data){credential=data.credential;account=data.account;localStorage.setItem('tt-online-credential',credential);requestedView==='profile'?profile():home()}
async function home(){const board=await api('/api/leaderboard').catch(()=>({scores:[]}));app.innerHTML=`<section class="grid"><div class="panel stack"><div class="row between"><div><div class="muted">WELCOME BACK</div><h1>${esc(account.username)}</h1></div><img class="avatar profile-circle" src="${image(account.avatarPower)}"></div><div class="cards"><div class="card"><strong>${account.totalWins}</strong><div class="muted">Total wins</div></div><div class="card"><strong>${account.highScore}</strong><div class="muted">Highest gold</div></div><div class="card"><strong>${account.achievements.length}</strong><div class="muted">Badges earned</div></div></div><div class="row"><button class="primary" data-act="create-room">Create room</button><input id="room-code" maxlength="6" placeholder="ROOM CODE"><button data-act="join-room">Join</button></div><div class="notice">Online rooms need at least two real players on separate devices. If the free online harbor is full, offline bot and pass-and-play games stay available.</div><div class="row"><button data-act="profile">Player profile</button><button data-act="achievements">Achievements</button><button data-act="settings">Player settings</button><a href="index.html"><button>Offline game</button></a></div></div><aside class="panel"><h2>Top fortunes</h2><table class="leaderboard"><tbody>${board.scores.map((s,i)=>`<tr><td>${i+1}</td><td>${esc(s.username)}</td><td>${s.score}</td><td>${esc(s.power)}</td></tr>`).join('')||'<tr><td>No completed online voyages yet.</td></tr>'}</tbody></table></aside></section>`}
function profile(){app.innerHTML=`<section class="panel stack"><div class="row between"><h1>Captain profile</h1>${requestedView==='profile'?'<a href="index.html"><button>Back to home</button></a>':'<button data-act="home">Back</button>'}</div><div class="row"><img class="avatar profile-circle" src="${image(account.avatarPower)}"><h2>${esc(account.username)}</h2></div><div class="cards"><div class="card"><h2>${account.totalWins}</h2><span>Total wins</span></div><div class="card"><h2>${account.highScore}</h2><span>Highest gold</span></div></div><h2>Wins by power</h2><div class="cards">${catalog.map(p=>`<div class="card">${esc(p.name)} <strong>${account.powerWins.find(x=>x.power===p.name)?.wins||0}</strong></div>`).join('')}</div></section>`}
async function achievements(){const data=await api('/api/achievements');const won=new Set(account.achievements.map(x=>x.achievement_id));app.innerHTML=`<section class="panel stack"><div class="row between"><h1>Achievements</h1><button data-act="home">Back</button></div><div class="badge-grid">${data.achievements.map((a,i)=>`<article class="achievement ${won.has(a.id)?'earned':'locked'}"><span class="badge">${won.has(a.id)?['⚓','★','♛','✦'][i%4]:'?'}</span><div><strong>${esc(a.name)}</strong><p>${esc(a.description)}</p></div></article>`).join('')}</div></section>`}
function settings(){const choices=['Pirate',...catalog.map(p=>p.name)];app.innerHTML=`<section class="panel stack"><div class="row between"><h1>Player settings</h1><button data-act="home">Back</button></div><h2>Profile picture</h2><div class="portrait-picker">${choices.map(name=>`<button class="portrait-choice ${account.avatarPower===name?'selected':''}" data-avatar="${esc(name)}"><img src="${image(name)}" alt="${esc(name)}"><span>${esc(name)}</span></button>`).join('')}</div><h2>Account recovery</h2><p class="muted">Generate a private recovery code when you are ready to protect this captain. Creating a new code replaces any older one.</p><button data-act="recovery-code">Show a new recovery code</button><div id="recovery-result"></div><div class="notice"><strong>Changing your username creates a fresh captain.</strong> Wins, scores, and achievements on this captain will be erased.</div><div class="row"><input id="new-username" maxlength="20" placeholder="New username"><button class="danger" data-act="reset-account">Reset progress & rename</button></div></section>`}
async function createRoom(){const d=await api('/api/rooms/create',{method:'POST',body:JSON.stringify({deviceId})});roomId=d.roomId;connectRoom()}
function joinRoom(){roomId=$('#room-code').value.trim().toUpperCase();if(roomId.length!==6)return toast('Enter the six-character room code.');connectRoom()}
function connectRoom(){localStorage.setItem('tt-online-room',roomId);if(socket)socket.close();const url=`${API.replace('https','wss')}/api/rooms/${roomId}/ws?deviceId=${encodeURIComponent(deviceId)}`;socket=new WebSocket(url,`tt-auth.${credential}`);connection.textContent='Connecting…';socket.onopen=()=>{connection.textContent='Connected';connection.className='pill live'};socket.onclose=()=>{connection.textContent='Reconnecting…';connection.className='pill bad';setTimeout(()=>roomId&&connectRoom(),1800)};socket.onerror=()=>toast('Could not reach that room.');socket.onmessage=e=>{const msg=JSON.parse(e.data);if(msg.type==='error')toast(msg.message);if(msg.type==='state'){room=msg.state;renderRoom()}}}
const send=data=>socket?.readyState===1&&socket.send(JSON.stringify(data));
document.addEventListener('pointerdown',e=>{if(e.target.closest('[data-act="leave-room"]'))send({type:'leave'})},{capture:true});
function renderRoom(){clearInterval(timer);if(room.phase==='lobby')renderLobby();else if(room.phase==='choosing')renderPowerChoice();else{localStorage.setItem('tt-online-room',roomId);location.href=`index.html?online=${encodeURIComponent(roomId)}`}}
function renderLobby(){const host=room.hostId===account.id;if(host&&!lobbyDraft)lobbyDraft={totalPlayers:Math.max(room.totalPlayers,room.members.length),timeFormat:room.timeFormat||'long',botActions:room.botActions||'fast'};if(host&&lobbyDraft.totalPlayers<room.members.length)lobbyDraft.totalPlayers=room.members.length;const s=host?lobbyDraft:room,reason=room.members.length<2?'At least two real players on separate devices must join.':'';app.innerHTML=`<section class="grid"><div class="panel stack"><div class="row between"><div><div class="muted">ROOM CODE</div><div class="room-code">${roomId}</div></div><button data-act="leave-room">Leave</button></div>${host?`<div class="row"><label>Total players<select id="total">${[3,4,5,6,7,8].filter(n=>n>=room.members.length).map(n=>`<option ${n===s.totalPlayers?'selected':''}>${n}</option>`)}</select></label><label>Turn time<select id="time-format">${[['short','Short · 10 sec'],['medium','Medium · 30 sec'],['long','Long · 1 min']].map(([v,l])=>`<option value="${v}" ${v===s.timeFormat?'selected':''}>${l}</option>`)}</select></label><label>Bot actions<select id="bot-actions">${[['fast','Fast · draw at 5 sec'],['slow','Slow · draw at 10 sec'],['controlled','Controlled by host']].map(([v,l])=>`<option value="${v}" ${v===s.botActions?'selected':''}>${l}</option>`)}</select></label><button data-act="configure">Update room</button></div>`:`<p class="muted">${room.totalPlayers} total captains · missing seats become bots · ${esc((room.timeFormat||'long').toUpperCase())} turns · ${esc((room.botActions||'fast').toUpperCase())} bots.</p>`}<div><h2>Crew</h2>${room.members.map(m=>`<div class="member"><div><strong>${esc(m.username)}</strong> ${m.accountId===room.hostId?'⚓':''}<br><small>${m.connected?'Connected':'Disconnected'}</small></div>${host&&m.accountId!==account.id?`<div><button data-member="${m.accountId}" data-act="${m.muted?'unmute':'mute'}">${m.muted?'Unmute':'Mute'}</button> <button data-member="${m.accountId}" data-act="kick">Kick</button> <button class="danger" data-member="${m.accountId}" data-act="ban">Ban</button></div>`:''}</div>`).join('')}</div>${host?`<div class="notice">${esc(reason||`${room.totalPlayers-room.members.length} bot${room.totalPlayers-room.members.length===1?'':'s'} will fill the remaining seats. Power choices begin after Start Voyage.`)}</div><button class="primary" data-act="start-online" ${reason?'disabled':''}>Start voyage</button>`:'<p>Waiting for the host to start the voyage…</p>'}</div>${chatPanel()}</section>`}
function renderPowerChoice(){const me=room.members.find(m=>m.accountId===account.id),offers=me?.offers||[];app.innerHTML=`<div class="power-lock"><section class="power-lock-card"><span class="muted">PRIVATE CAPTAIN CHOICE</span><h1>Choose your power</h1><div id="power-clock" class="room-code"></div><p>Only you can see these two choices. One is chosen randomly when time runs out.</p><div class="cards power-offers">${offers.map(name=>{const p=catalog.find(x=>x.name===name);return `<button class="power ${me.power===name?'selected':''}" data-power="${esc(name)}" ${me.power?'disabled':''}><img src="${image(name)}"><h2>${esc(name)}</h2><p>${esc(p?.description||'')}</p></button>`}).join('')}</div>${me?.power?'<div class="notice">Power locked in. Waiting for the other captains…</div>':''}</section></div>`;const tick=()=>{const e=$('#power-clock');if(e)e.textContent=Math.ceil(Math.max(0,(room.powerDeadline-Date.now())/1000))+'s'};tick();timer=setInterval(tick,250)}
function chatPanel(){return `<aside class="panel stack"><h2>Room chat</h2><div class="chat" id="chat">${room.chat.map(m=>`<p><strong>${esc(m.username)}</strong> ${esc(m.text)}</p>`).join('')}</div><div class="row"><input id="chat-input" maxlength="240" placeholder="Message the fleet"><button data-act="chat">Send</button></div></aside>`}
function renderGame(){const s=room.snapshot,g=s?.game,req=s?.request;if(!g)return;const deadline=room.turnDeadline||0;app.innerHTML=`<section class="grid"><div class="panel stack"><div class="row between"><div><span class="muted">ROUND ${g.round}/${g.maxRounds}</span><h1>${g.safe?'Calm waters':'The storm'}</h1></div><div><div class="muted">Shared pot</div><div class="room-code">${Math.round(g.pot)} gold</div></div></div><div class="players">${g.players.map((p,i)=>`<div class="player ${i===g.current?'current':''}"><strong>${esc(p.name)}</strong><div>${esc(p.power)}</div><div class="numbers"><span>⛵ ${p.ships}</span><span>◈ ${Math.round(p.gold)}</span></div><small>${esc(p.status)}</small></div>`).join('')}</div>${g.last?`<div class="card"><span class="muted">Last card</span><h2>${esc(g.last.name||g.last.kind||g.last)}</h2></div>`:''}<div class="prompt"><div id="timer" class="timer"></div><h2>${esc(req?.title||'Voyage complete')}</h2><p class="detail">${esc(req?.detail||'Final fortunes have been counted.')}</p><div class="row" style="justify-content:center">${(req?.options||[]).map(o=>`<button class="${o.value==='stay'?'primary':''}" data-answer="${esc(o.value)}">${esc(o.label)}</button>`).join('')}</div></div></div>${chatPanel()}</section>`;const tick=()=>{const e=$('#timer');if(!e)return;const left=Math.max(0,deadline-Date.now());e.textContent=req?.kind==='turn'?`${(left/1000).toFixed(1)}s`:'';document.querySelectorAll('[data-answer="stay"]').forEach(b=>b.disabled=Date.now()<(room.drawAllowedAt||0))};tick();timer=setInterval(tick,100)}
document.addEventListener('change',e=>{if(!lobbyDraft)return;const ids={total:'totalPlayers','time-format':'timeFormat','bot-actions':'botActions'},key=ids[e.target.id];if(key)lobbyDraft[key]=key==='totalPlayers'?+e.target.value:e.target.value});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{const a=b.dataset.act;if(a==='create-account'){const d=await api('/api/account/create',{method:'POST',body:JSON.stringify({username:$('#username').value})});saveAuth(d)}if(a==='show-recover')recoveryForm();if(a==='recover'){const d=await api('/api/account/recover',{method:'POST',body:JSON.stringify({username:$('#username').value,recoveryCode:$('#recovery').value})});saveAuth(d)}if(a==='signin')signIn();if(a==='home')home();if(a==='profile')profile();if(a==='achievements')achievements();if(a==='settings')settings();if(a==='recovery-code'){const d=await api('/api/account/recovery',{method:'POST'});$('#recovery-result').innerHTML=`<div class="recovery">${esc(d.recoveryCode)}</div><p class="muted">Keep this private. It is now the only recovery code for this captain.</p>`}if(a==='create-room')await createRoom();if(a==='join-room')joinRoom();if(a==='leave-room'){localStorage.removeItem('tt-online-room');roomId='';socket?.close();socket=null;lobbyDraft=null;home()}if(a==='configure')send({type:'configure',...lobbyDraft});if(a==='deal')send({type:'offerPowers'});if(a==='start-online'){send({type:'configure',...lobbyDraft});send({type:'start'})}if(a==='chat'){const input=$('#chat-input');if(input.value.trim())send({type:'chat',message:input.value});input.value=''}if(['kick','ban','mute','unmute'].includes(a))send({type:a,accountId:b.dataset.member});if(b.dataset.power)send({type:'choosePower',power:b.dataset.power});if(b.dataset.avatar){const d=await api('/api/account/avatar',{method:'POST',body:JSON.stringify({avatarPower:b.dataset.avatar})});account=d.account;settings()}if(a==='reset-account'){const name=$('#new-username').value;if(!confirm(`Erase all progress for ${account.username} and become ${name}? This cannot be undone.`))return;const d=await api('/api/account/reset',{method:'POST',body:JSON.stringify({username:name,avatarPower:account.avatarPower})});saveAuth(d)}}catch(err){toast(err.message)}});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.id==='chat-input')document.querySelector('[data-act="chat"]')?.click()});
const renderLobbyWithCurrentTiming=renderLobby;renderLobby=()=>{renderLobbyWithCurrentTiming();const select=$('#bot-actions');if(select){select.querySelector('[value="fast"]').textContent='Fast · draw at 3 sec';select.querySelector('[value="slow"]').textContent='Slow · draw at 8 sec'}};
boot().catch(err=>{app.innerHTML=`<section class="panel hero"><h1>Online harbor unavailable</h1><p class="error">${esc(err.message)}</p><a href="index.html">Offline play is still available.</a></section>`});
